### ISSUE TITLE
How to dynamically create & provision a vector

### ISSUE THREAD

**Issue by yoshuawuyts** [killercup/roff-rs#3]
I've started work on `man`, but I'm having trouble calling `page.section()` with a dynamically created vector. What's the right approach on how to do this?

Example code of what I'm trying to compile is here: https://github.com/rust-clique/man/blob/man-gen/src/man/mod.rs#L106.

Thanks!

## Log
```txt
Thursday, July 5th, 2018
00:42 <yoshuawuyts> killercup: started work on the man impl today, and ran into a troff question
00:42 <yoshuawuyts> killercup: trying to dynamically create a vector of authors, but not sure how to pass it into troff-rs https://github.com/rust-clique/man/blob/man-gen/src/man/mod.rs#L106
00:44 <yoshuawuyts> killercup: the line ^ isn't compiling. I reckon you might know how to work around it, haha
```

**Comment by epage** [comment]
I'm curious, why does `section` accept a slice rather than an `Iterator`?

**Comment by killercup** [comment]
@yoshuawuyts you are calling `Roff::section(&str, &Vec<[String, String]>)`, but only `Roff::section(&str, &Vec<String>)` is possible,

Your array is `[bold(author), email]`, so I can see what you are aiming for. Can you try if this works for you?

```rust
let mut auth_values = vec![];
for author in authors.iter() {
  auth_values.push(roff::bold(&author.name));

  if let Some(ref email) = author.email {
    auth_values.push(format!("- {:?}", email))
  };
}
```

**Comment by yoshuawuyts** [comment]
Worked like a charm!
